"""empty message

Revision ID: 51e4f36650c3
Revises: a33fbbab7fdf
Create Date: 2022-12-04 22:44:09.473723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e4f36650c3'
down_revision = 'a33fbbab7fdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requisitions', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requisitions', sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
