"""empty message

Revision ID: 85f5a92c0ced
Revises: 83f494703050
Create Date: 2022-12-05 12:30:37.164474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f5a92c0ced'
down_revision = '83f494703050'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_services', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('e_services', 'tag')
    op.add_column('kitchen_products', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('kitchen_products', 'tag')
    op.add_column('material_requests', sa.Column('accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_requests', 'accepted')
    op.add_column('kitchen_products', sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('kitchen_products', 'description')
    op.add_column('e_services', sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('e_services', 'description')
    # ### end Alembic commands ###
