"""empty message

Revision ID: a33fbbab7fdf
Revises: 8aa21bc5e5f0
Create Date: 2022-12-04 22:21:26.886482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33fbbab7fdf'
down_revision = '8aa21bc5e5f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_services', sa.Column('tag', sa.String(), nullable=True))
    op.drop_column('e_services', 'description')
    op.add_column('kitchen_products', sa.Column('tag', sa.String(), nullable=True))
    op.drop_column('kitchen_products', 'description')
    op.add_column('material_requests', sa.Column('tag', sa.String(), nullable=True))
    op.drop_column('material_requests', 'description')
    op.add_column('requisitions', sa.Column('tag', sa.String(), nullable=True))
    op.drop_column('requisitions', 'description')
    op.add_column('sales', sa.Column('tag', sa.String(), nullable=True))
    op.drop_column('sales', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('sales', 'tag')
    op.add_column('requisitions', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('requisitions', 'tag')
    op.add_column('material_requests', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('material_requests', 'tag')
    op.add_column('kitchen_products', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('kitchen_products', 'tag')
    op.add_column('e_services', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('e_services', 'tag')
    # ### end Alembic commands ###
