"""empty message

Revision ID: b1c40fa92f93
Revises: 85f5a92c0ced
Create Date: 2022-12-05 21:45:06.598689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c40fa92f93'
down_revision = '85f5a92c0ced'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Enum('sale', 'eservice', 'purchase', name='cashlabel'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('label_id', sa.String(), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_id')
    )
    op.alter_column('requisitions', 'stock_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requisitions', 'stock_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('cash')
    # ### end Alembic commands ###
