"""empty message

Revision ID: d7f397c11e42
Revises: 41d840545e66
Create Date: 2022-12-21 21:06:39.208259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f397c11e42'
down_revision = '41d840545e66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_items', sa.Column('remaining', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_items', 'remaining')
    # ### end Alembic commands ###
